### ISSUE TITLE
NullPointerException throws in initial run

### ISSUE THREAD

**Issue by shandanjay** [dheerajpille/minimaList#1]
https://github.com/dheerajpille/minimaList/blob/21646e00eaedadf1d6fc7b2894afa5f327270304/app/src/main/java/com/dheeraj/pille/minimalist/RecyclerAdapter.java#L114

**Comment by shandanjay** [comment]
I suggest following fix. Please take a look.
```
    @Override
    public int getItemCount() {
        if (taskArrayList instanceof ArrayList)
                    return taskArrayList.size();
        else return 0;
    }
```

**Comment by dheerajpille** [comment]
I fixed the error by initializing the taskArrayList. Thank you for presenting this issue.
`private ArrayList<Task> taskArrayList = new ArrayList<Task>();`
